<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report['month_label'] }} — Fast Home Service</title>

    <style>
        /* Extra room at the foot for the repeating footer, which is painted
           into the margin rather than in the flow. */
        @page { margin: 16mm 16mm 22mm; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111;
            padding: 0;
            margin: 0;
        }

        .masthead { width: 100%; Margin-bottom: 50px; text-align: center; }
        .masthead td { vertical-align: top; }
        .business { font-size: 25px; font-weight: bold; }
        .subtitle { color: #666; padding-top: 2px; font-weight: 500 }
        .period { text-align: right; font-weight: bold; }

        h2 {
            font-size: 16px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            color: #666;
            margin: 22px 0 6px;
        }

        table.figures { width: 100%; border-collapse: collapse; }
        table.figures td { border-bottom: 1px solid #e5e5e5; padding: 6px 0; }
        table.figures td.amount { text-align: right; white-space: nowrap; }

        .hint { color: #777; font-size: 9px; padding-top: 1px; }
        .emphasis td { font-weight: bold; }
        .total td { font-weight: bold; font-size: 13px; border-bottom: 2px solid #111; }
        .loss { color: #b91c1c; }

        /* In the normal flow, not positioned: an absolute box with a negative
           offset can be pushed off the sheet or onto a second page. */
        .provenance {
            color: #777;
            font-size: 10px;
            padding-top: 8px;
            margin: 5px auto 0;
            max-width: 340px;
            border-top: 1px solid #d4d4d4;
        }

        .watermark {
            position: fixed;
            top: 27%;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 46px;
            font-weight: 700;
            letter-spacing: 0.08em;
            color: #f0f0f0;
            z-index: -1;
            transform: rotate(-40deg);
        }

        .footer-note {
            position: fixed;
            left: 0;
            right: 0;
            bottom: -14mm;
            padding-top: 5px;
            font-size: 8px;
            line-height: 1.4;
            color: #777;
            border-top: 1px solid #d4d4d4;
        }

        /* An empty block dompdf breaks after — more reliable here than
           page-break-before on the heading itself. */
        .page-break { page-break-after: always; }

        table.items { width: 100%; border-collapse: collapse; }
        table.items th {
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            color: #666;
            border-bottom: 1px solid #999;
            padding: 6px 4px;
        }
        table.items td { border-bottom: 1px solid #e5e5e5; padding: 6px 4px; }
        table.items td.number,
        table.items th.number { text-align: right; white-space: nowrap; }
        table.items tfoot td {
            font-weight: bold;
            border-top: 1px solid #111;
            border-bottom: none;
        }
    </style>
</head>

<body>
    {{-- First in the body so it is painted before the content that sits over
         it. Fixed, so it appears on every page. --}}
    <div class="watermark">Fast Home Service</div>

    {{-- Declared before the content it sits under. A fixed box is painted on
         every page, so this is the running footer for the whole document. --}}
    <div class="footer-note">
        Generated by {{ $generatedBy }} on {{ $generatedAt }}. Figures are derived from the
        records as they stand now, so a correction made later will change them.
    </div>

    <table class="masthead">
        <tr>
            <td>
                <div class="business">Fast Home Service</div>
                <div class="subtitle">{{ $report['month_label'] }} report</div>
                {{-- Provenance belongs with the title rather than at the foot:
                     who produced this and when is the first thing a reader
                     needs in order to judge the figures below. --}}
                <div class="provenance">
                    Generated by {{ $generatedBy }} on {{ $generatedAt }}.
                </div>
            </td>
        </tr>
    </table>

    <h2>Trading</h2>
    <table class="figures">
        <tr>
            <td>Revenue<div class="hint">Everything billed to customers</div></td>
            <td class="amount">{{ $money($report['revenue']) }}</td>
        </tr>
        <tr>
            <td>Sales<div class="hint">Orders recorded</div></td>
            <td class="amount">{{ number_format($report['sales_count']) }}</td>
        </tr>
        <tr>
            <td>Average sale<div class="hint">Revenue per order</div></td>
            <td class="amount">{{ $money($report['average_order']) }}</td>
        </tr>
    </table>

    <h2>Profit</h2>
    <table class="figures">
        <tr>
            <td>Revenue</td>
            <td class="amount">{{ $money($report['revenue']) }}</td>
        </tr>
        <tr>
            <td>Cost of goods sold<div class="hint">What the goods sold cost</div></td>
            <td class="amount">{{ $money(-$report['cogs']) }}</td>
        </tr>
        <tr class="emphasis">
            <td>Gross profit</td>
            <td class="amount">{{ $money($report['gross_profit']) }}</td>
        </tr>
        <tr>
            <td>Expenses<div class="hint">Running costs and consignment transport</div></td>
            <td class="amount">{{ $money(-$report['expenses']) }}</td>
        </tr>
        <tr class="total">
            <td>Net profit</td>
            {{-- Only the bottom line is tinted: colouring every ordinary cost
                 would make normal trading look like a problem. --}}
            <td class="amount @if ($report['net_profit'] < 0) loss @endif">{{ $money($report['net_profit']) }}</td>
        </tr>
    </table>

    {{-- Only when it differs from revenue. Everything billed was collected in
         the same month, so a Cash section would restate the figure above it and
         tell the reader nothing. A gap either way is the thing worth showing:
         money still owed, or an older debt settled this month. --}}
    @if ($report['collected'] !== $report['revenue'])
        <h2>Cash</h2>
        <table class="figures">
            <tr>
                <td>
                    Money received
                    <div class="hint">Collected this month, whichever month the sale was in</div>
                </td>
                <td class="amount">{{ $money($report['collected']) }}</td>
            </tr>
        </table>
    @endif

    {{-- Nothing sold means nothing to break onto a second sheet, so an empty
         month stays one page rather than gaining a blank one. --}}
    @if ($report['items'] !== [])
        <div class="page-break"></div>

        <h2>Sales by item</h2>
        <table class="items">
            <thead>
                <tr>
                    <th>Item</th>
                    <th class="number">Sold</th>
                    <th class="number">Swap</th>
                    <th class="number">Outright</th>
                    <th class="number">Revenue</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report['items'] as $item)
                    <tr>
                        <td>{{ $item['name'] }}</td>
                        <td class="number">{{ number_format($item['quantity']) }}</td>
                        {{-- A swap returns the cylinder; an outright sale does
                             not. A month heavy on the right-hand column is
                             draining shells out of circulation. --}}
                        <td class="number">{{ number_format($item['swapped']) }}</td>
                        <td class="number">{{ number_format($item['outright']) }}</td>
                        <td class="number">{{ $money($item['revenue']) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td class="number">{{ number_format(collect($report['items'])->sum('quantity')) }}</td>
                    <td class="number">{{ number_format(collect($report['items'])->sum('swapped')) }}</td>
                    <td class="number">{{ number_format(collect($report['items'])->sum('outright')) }}</td>
                    {{-- Ties back to the revenue on page one: the same money,
                         divided by what produced it. --}}
                    <td class="number">{{ $money(collect($report['items'])->sum('revenue')) }}</td>
                </tr>
            </tfoot>
        </table>
    @endif

</body>
</html>
